# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c96a04443c5a673fb785a2834e9c5d3095a48705a530e8d6d683d09513bb17d855ce4049d0ac8978a4e658d4e87f8debf6462c246531608ff30674d8ebcc81ee

test:
  secret_key_base: da33af450ebc3ae59eb0c36be577f526fe5b264dbd407a1747cc0ae9fafc37cf31d78e9c9f0f3f4e5032d7af4157efdb231e2858051aa87f35b8118b81af5bb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
